# Generated by Django 5.1.6 on 2025-03-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='location',
        ),
    ]
