# Generated by Django 5.1.6 on 2025-03-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
    ]
