# Generated by Django 5.1.6 on 2025-03-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_movie_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.ManyToManyField(related_name='movies', to='main.moviedate'),
        ),
    ]
